# Generated by Django 3.0 on 2022-01-14 07:55

import books.services
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Имя автора', max_length=128, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Фамилия автора', max_length=128, verbose_name='Фамилия')),
                ('image', models.ImageField(blank=True, help_text='Фото автора', upload_to='author/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Жанр книги', max_length=128, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_pdf', models.FileField(help_text='Формат .pdf не более 100MB', upload_to='pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), books.services.validate_size_pdf], verbose_name='pdf')),
                ('year', models.PositiveIntegerField(help_text='Год издания', verbose_name='Год')),
                ('title', models.CharField(help_text='Название книги', max_length=256, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Описание книги', max_length=1024, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Формат .jpg не более 2MB', upload_to='book_cover/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg']), books.services.validate_size_image], verbose_name='Обложка')),
                ('draft', models.BooleanField(default=True, verbose_name='Черновик')),
                ('author_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_by', to='books.Author', verbose_name='Автор')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('genre', models.ManyToManyField(blank=True, related_name='genre', to='books.Genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-year'],
            },
        ),
    ]
